# Generated by Django 5.1 on 2024-10-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_pt',
            field=models.TextField(blank=True, verbose_name='Descrição em Português'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título em Português'),
        ),
    ]
