# Generated by Django 5.1 on 2024-10-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_description_pt_project_title_pt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Video Link'),
        ),
    ]
