# Generated by Django 5.1 on 2024-10-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['featured_order']},
        ),
        migrations.AddField(
            model_name='project',
            name='featured_order',
            field=models.IntegerField(default=0),
        ),
    ]
